services:
  console-web:
    build:
      context: ../../../../edge/console-web
      dockerfile: Dockerfile
    container_name: octal-console
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - octal-network

networks:
  octal-network:
    driver: bridge
